import { MigrationInterface, QueryRunner } from "typeorm";

export class AddSamplesDateTimeInternalNote1777201416810 implements MigrationInterface {
    name = 'AddSamplesDateTimeInternalNote1777201416810'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "colors" DROP CONSTRAINT "FK_colors_style"`);
        await queryRunner.query(`ALTER TABLE "samples" DROP CONSTRAINT "FK_samples_color"`);
        await queryRunner.query(`ALTER TABLE "samples" DROP CONSTRAINT "FK_samples_style"`);
        await queryRunner.query(`ALTER TABLE "materials" DROP CONSTRAINT "FK_materials_material_group"`);
        await queryRunner.query(`ALTER TABLE "draft_bom_lines" DROP CONSTRAINT "FK_draft_bom_lines_material"`);
        await queryRunner.query(`ALTER TABLE "draft_bom_lines" DROP CONSTRAINT "FK_draft_bom_lines_draft_bom"`);
        await queryRunner.query(`ALTER TABLE "draft_boms" DROP CONSTRAINT "FK_draft_boms_color"`);
        await queryRunner.query(`ALTER TABLE "draft_boms" DROP CONSTRAINT "FK_draft_boms_style"`);
        await queryRunner.query(`ALTER TABLE "style_as3b_steps" DROP CONSTRAINT "FK_style_as3b_steps_style"`);
        await queryRunner.query(`ALTER TABLE "style_production_docs" DROP CONSTRAINT "FK_style_production_docs_style"`);
        await queryRunner.query(`ALTER TABLE "style_version_logs" DROP CONSTRAINT "FK_style_version_logs_style"`);
        await queryRunner.query(`ALTER TABLE "line_color_cards" DROP CONSTRAINT "FK_line_color_cards_line_color"`);
        await queryRunner.query(`ALTER TABLE "line_samples" DROP CONSTRAINT "FK_line_samples_color"`);
        await queryRunner.query(`ALTER TABLE "po_lines" DROP CONSTRAINT "FK_po_lines_style"`);
        await queryRunner.query(`ALTER TABLE "stock_movements" DROP CONSTRAINT "FK_stock_movements_user"`);
        await queryRunner.query(`ALTER TABLE "stock_movements" DROP CONSTRAINT "FK_stock_movements_material"`);
        await queryRunner.query(`ALTER TABLE "material_sizes" DROP CONSTRAINT "FK_material_sizes_material"`);
        await queryRunner.query(`ALTER TABLE "master_po_lines" DROP CONSTRAINT "FK_master_po_lines_po_line"`);
        await queryRunner.query(`ALTER TABLE "master_po_lines" DROP CONSTRAINT "FK_master_po_lines_master_po"`);
        await queryRunner.query(`ALTER TABLE "doc_files" DROP CONSTRAINT "FK_doc_files_folder"`);
        await queryRunner.query(`ALTER TABLE "boms" DROP CONSTRAINT "FK_boms_master_po"`);
        await queryRunner.query(`ALTER TABLE "boms" DROP CONSTRAINT "FK_boms_style"`);
        await queryRunner.query(`DROP INDEX "public"."idx_colors_style_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_colors_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_samples_style_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_samples_color_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_samples_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_draft_boms_style_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_draft_boms_color_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_draft_boms_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_style_as3b_steps_style_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_style_as3b_steps_order_index"`);
        await queryRunner.query(`DROP INDEX "public"."idx_style_production_docs_style_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_styles_style_code"`);
        await queryRunner.query(`DROP INDEX "public"."idx_styles_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_style_version_logs_style_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_style_version_logs_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_line_color_cards_line_color_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_po_lines_style_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_stock_movements_material_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_stock_movements_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_material_sizes_material_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_master_po_lines_master_po_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_master_po_lines_po_line_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_master_pos_code"`);
        await queryRunner.query(`DROP INDEX "public"."idx_master_pos_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_master_pos_shipping_month"`);
        await queryRunner.query(`DROP INDEX "public"."idx_boms_style_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_boms_master_po_id"`);
        await queryRunner.query(`ALTER TABLE "material_sizes" DROP CONSTRAINT "UQ_material_sizes_material_size"`);
        await queryRunner.query(`ALTER TABLE "line_samples" DROP COLUMN "color_id"`);
        await queryRunner.query(`ALTER TABLE "po_lines" DROP COLUMN "style_id"`);
        await queryRunner.query(`ALTER TABLE "boms" DROP COLUMN "style_id"`);
        await queryRunner.query(`ALTER TABLE "boms" DROP COLUMN "master_po_id"`);
        await queryRunner.query(`ALTER TABLE "samples" ADD "date_time" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "samples" ADD "internal_note" text`);
        await queryRunner.query(`ALTER TABLE "colors" ALTER COLUMN "style_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "colors" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."colors_status_enum" AS ENUM('Draft', 'Active', 'Inactive')`);
        await queryRunner.query(`ALTER TABLE "colors" ADD "status" "public"."colors_status_enum" NOT NULL DEFAULT 'Draft'`);
        await queryRunner.query(`ALTER TABLE "samples" DROP COLUMN "sample_type"`);
        await queryRunner.query(`CREATE TYPE "public"."samples_sample_type_enum" AS ENUM('TechPack', 'Sketch', 'FitSample', 'Quotation')`);
        await queryRunner.query(`ALTER TABLE "samples" ADD "sample_type" "public"."samples_sample_type_enum" NOT NULL DEFAULT 'TechPack'`);
        await queryRunner.query(`ALTER TABLE "samples" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."samples_status_enum" AS ENUM('Draft', 'In_Analysis', 'Analyzed', 'Approved')`);
        await queryRunner.query(`ALTER TABLE "samples" ADD "status" "public"."samples_status_enum" DEFAULT 'Draft'`);
        await queryRunner.query(`ALTER TABLE "draft_boms" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."draft_boms_status_enum" AS ENUM('Draft', 'Submitted', 'Approved')`);
        await queryRunner.query(`ALTER TABLE "draft_boms" ADD "status" "public"."draft_boms_status_enum" NOT NULL DEFAULT 'Draft'`);
        await queryRunner.query(`ALTER TABLE "styles" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."styles_status_enum" AS ENUM('Draft', 'Approved', 'Active')`);
        await queryRunner.query(`ALTER TABLE "styles" ADD "status" "public"."styles_status_enum" NOT NULL DEFAULT 'Draft'`);
        await queryRunner.query(`ALTER TABLE "line_color_cards" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."line_color_cards_status_enum" AS ENUM('active', 'inactive')`);
        await queryRunner.query(`ALTER TABLE "line_color_cards" ADD "status" "public"."line_color_cards_status_enum" NOT NULL DEFAULT 'active'`);
        await queryRunner.query(`ALTER TYPE "public"."po_lines_status_enum" RENAME TO "po_lines_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."po_lines_previous_status_enum" AS ENUM('Draft', 'In_Review', 'Sampling', 'Final', 'Cancelled')`);
        await queryRunner.query(`ALTER TABLE "po_lines" ALTER COLUMN "previous_status" TYPE "public"."po_lines_previous_status_enum" USING "previous_status"::"text"::"public"."po_lines_previous_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."po_lines_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "master_pos" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."master_pos_status_enum" AS ENUM('Draft', 'Confirmed', 'Partially_Shipped', 'Shipped')`);
        await queryRunner.query(`ALTER TABLE "master_pos" ADD "status" "public"."master_pos_status_enum" NOT NULL DEFAULT 'Draft'`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_6713755c9930c827c91cd80c97" ON "material_sizes" ("material_id", "size") `);
        await queryRunner.query(`ALTER TABLE "colors" ADD CONSTRAINT "FK_2755f5c3c12ce91259b3290b77b" FOREIGN KEY ("style_id") REFERENCES "styles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "samples" ADD CONSTRAINT "FK_78786f9c337cb27d6c452cbf67d" FOREIGN KEY ("style_id") REFERENCES "styles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "samples" ADD CONSTRAINT "FK_0963fdf415b99350f6b96513880" FOREIGN KEY ("color_id") REFERENCES "colors"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "materials" ADD CONSTRAINT "FK_3a7993738b9d93e864811a03d52" FOREIGN KEY ("material_group_id") REFERENCES "material_groups"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "draft_bom_lines" ADD CONSTRAINT "FK_e776df6c7559ddfa977576e6c84" FOREIGN KEY ("draft_bom_id") REFERENCES "draft_boms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "draft_bom_lines" ADD CONSTRAINT "FK_a4f4d8a75aa70f90885167e4163" FOREIGN KEY ("master_material_id") REFERENCES "materials"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "draft_boms" ADD CONSTRAINT "FK_7479e3d5f34727f6113adb18a1f" FOREIGN KEY ("style_id") REFERENCES "styles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "draft_boms" ADD CONSTRAINT "FK_5cee347416a10073dab68775d04" FOREIGN KEY ("color_id") REFERENCES "colors"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "style_as3b_steps" ADD CONSTRAINT "FK_556acb2cd5b041402640c5148fc" FOREIGN KEY ("style_id") REFERENCES "styles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "style_production_docs" ADD CONSTRAINT "FK_d3e8f180af324c2a96437394ef3" FOREIGN KEY ("style_id") REFERENCES "styles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "line_color_cards" ADD CONSTRAINT "FK_c30868ffdd3627c11bbeaaade18" FOREIGN KEY ("line_color_id") REFERENCES "line_colors"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_movements" ADD CONSTRAINT "FK_8bf5e361bdce822486fee95e6ea" FOREIGN KEY ("material_id") REFERENCES "materials"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_sizes" ADD CONSTRAINT "FK_869dd76b31bcc3e4a289a6d706e" FOREIGN KEY ("material_id") REFERENCES "materials"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "master_po_lines" ADD CONSTRAINT "FK_4fd6178729af3ec73ab3ec8b133" FOREIGN KEY ("master_po_id") REFERENCES "master_pos"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "master_po_lines" ADD CONSTRAINT "FK_4bbff3330c1cc97944d99adb37c" FOREIGN KEY ("po_line_id") REFERENCES "po_lines"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "doc_files" ADD CONSTRAINT "FK_257c0d5e9d98c5092c39f3b7874" FOREIGN KEY ("folder_id") REFERENCES "doc_folders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "doc_files" DROP CONSTRAINT "FK_257c0d5e9d98c5092c39f3b7874"`);
        await queryRunner.query(`ALTER TABLE "master_po_lines" DROP CONSTRAINT "FK_4bbff3330c1cc97944d99adb37c"`);
        await queryRunner.query(`ALTER TABLE "master_po_lines" DROP CONSTRAINT "FK_4fd6178729af3ec73ab3ec8b133"`);
        await queryRunner.query(`ALTER TABLE "material_sizes" DROP CONSTRAINT "FK_869dd76b31bcc3e4a289a6d706e"`);
        await queryRunner.query(`ALTER TABLE "stock_movements" DROP CONSTRAINT "FK_8bf5e361bdce822486fee95e6ea"`);
        await queryRunner.query(`ALTER TABLE "line_color_cards" DROP CONSTRAINT "FK_c30868ffdd3627c11bbeaaade18"`);
        await queryRunner.query(`ALTER TABLE "style_production_docs" DROP CONSTRAINT "FK_d3e8f180af324c2a96437394ef3"`);
        await queryRunner.query(`ALTER TABLE "style_as3b_steps" DROP CONSTRAINT "FK_556acb2cd5b041402640c5148fc"`);
        await queryRunner.query(`ALTER TABLE "draft_boms" DROP CONSTRAINT "FK_5cee347416a10073dab68775d04"`);
        await queryRunner.query(`ALTER TABLE "draft_boms" DROP CONSTRAINT "FK_7479e3d5f34727f6113adb18a1f"`);
        await queryRunner.query(`ALTER TABLE "draft_bom_lines" DROP CONSTRAINT "FK_a4f4d8a75aa70f90885167e4163"`);
        await queryRunner.query(`ALTER TABLE "draft_bom_lines" DROP CONSTRAINT "FK_e776df6c7559ddfa977576e6c84"`);
        await queryRunner.query(`ALTER TABLE "materials" DROP CONSTRAINT "FK_3a7993738b9d93e864811a03d52"`);
        await queryRunner.query(`ALTER TABLE "samples" DROP CONSTRAINT "FK_0963fdf415b99350f6b96513880"`);
        await queryRunner.query(`ALTER TABLE "samples" DROP CONSTRAINT "FK_78786f9c337cb27d6c452cbf67d"`);
        await queryRunner.query(`ALTER TABLE "colors" DROP CONSTRAINT "FK_2755f5c3c12ce91259b3290b77b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6713755c9930c827c91cd80c97"`);
        await queryRunner.query(`ALTER TABLE "master_pos" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."master_pos_status_enum"`);
        await queryRunner.query(`ALTER TABLE "master_pos" ADD "status" character varying(50) NOT NULL DEFAULT 'Draft'`);
        await queryRunner.query(`CREATE TYPE "public"."po_lines_status_enum_old" AS ENUM('Draft', 'In_Review', 'Sampling', 'Final', 'Cancelled')`);
        await queryRunner.query(`ALTER TABLE "po_lines" ALTER COLUMN "previous_status" TYPE "public"."po_lines_status_enum_old" USING "previous_status"::"text"::"public"."po_lines_status_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."po_lines_previous_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."po_lines_status_enum_old" RENAME TO "po_lines_status_enum"`);
        await queryRunner.query(`ALTER TABLE "line_color_cards" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."line_color_cards_status_enum"`);
        await queryRunner.query(`ALTER TABLE "line_color_cards" ADD "status" character varying(20) NOT NULL DEFAULT 'active'`);
        await queryRunner.query(`ALTER TABLE "styles" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."styles_status_enum"`);
        await queryRunner.query(`ALTER TABLE "styles" ADD "status" character varying(50) NOT NULL DEFAULT 'Draft'`);
        await queryRunner.query(`ALTER TABLE "draft_boms" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."draft_boms_status_enum"`);
        await queryRunner.query(`ALTER TABLE "draft_boms" ADD "status" character varying(50) NOT NULL DEFAULT 'Draft'`);
        await queryRunner.query(`ALTER TABLE "samples" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."samples_status_enum"`);
        await queryRunner.query(`ALTER TABLE "samples" ADD "status" character varying(50) NOT NULL DEFAULT 'Draft'`);
        await queryRunner.query(`ALTER TABLE "samples" DROP COLUMN "sample_type"`);
        await queryRunner.query(`DROP TYPE "public"."samples_sample_type_enum"`);
        await queryRunner.query(`ALTER TABLE "samples" ADD "sample_type" character varying(50) NOT NULL DEFAULT 'TechPack'`);
        await queryRunner.query(`ALTER TABLE "colors" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."colors_status_enum"`);
        await queryRunner.query(`ALTER TABLE "colors" ADD "status" character varying(50) NOT NULL DEFAULT 'Draft'`);
        await queryRunner.query(`ALTER TABLE "colors" ALTER COLUMN "style_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "samples" DROP COLUMN "internal_note"`);
        await queryRunner.query(`ALTER TABLE "samples" DROP COLUMN "date_time"`);
        await queryRunner.query(`ALTER TABLE "boms" ADD "master_po_id" uuid`);
        await queryRunner.query(`ALTER TABLE "boms" ADD "style_id" uuid`);
        await queryRunner.query(`ALTER TABLE "po_lines" ADD "style_id" uuid`);
        await queryRunner.query(`ALTER TABLE "line_samples" ADD "color_id" uuid`);
        await queryRunner.query(`ALTER TABLE "material_sizes" ADD CONSTRAINT "UQ_material_sizes_material_size" UNIQUE ("material_id", "size")`);
        await queryRunner.query(`CREATE INDEX "idx_boms_master_po_id" ON "boms" ("master_po_id") `);
        await queryRunner.query(`CREATE INDEX "idx_boms_style_id" ON "boms" ("style_id") `);
        await queryRunner.query(`CREATE INDEX "idx_master_pos_shipping_month" ON "master_pos" ("shipping_month") `);
        await queryRunner.query(`CREATE INDEX "idx_master_pos_status" ON "master_pos" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_master_pos_code" ON "master_pos" ("master_po_code") `);
        await queryRunner.query(`CREATE INDEX "idx_master_po_lines_po_line_id" ON "master_po_lines" ("po_line_id") `);
        await queryRunner.query(`CREATE INDEX "idx_master_po_lines_master_po_id" ON "master_po_lines" ("master_po_id") `);
        await queryRunner.query(`CREATE INDEX "idx_material_sizes_material_id" ON "material_sizes" ("material_id") `);
        await queryRunner.query(`CREATE INDEX "idx_stock_movements_created_at" ON "stock_movements" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_stock_movements_material_id" ON "stock_movements" ("material_id") `);
        await queryRunner.query(`CREATE INDEX "idx_po_lines_style_id" ON "po_lines" ("style_id") `);
        await queryRunner.query(`CREATE INDEX "idx_line_color_cards_line_color_id" ON "line_color_cards" ("line_color_id") `);
        await queryRunner.query(`CREATE INDEX "idx_style_version_logs_created_at" ON "style_version_logs" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_style_version_logs_style_id" ON "style_version_logs" ("style_id") `);
        await queryRunner.query(`CREATE INDEX "idx_styles_status" ON "styles" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_styles_style_code" ON "styles" ("style_code") `);
        await queryRunner.query(`CREATE INDEX "idx_style_production_docs_style_id" ON "style_production_docs" ("style_id") `);
        await queryRunner.query(`CREATE INDEX "idx_style_as3b_steps_order_index" ON "style_as3b_steps" ("order_index") `);
        await queryRunner.query(`CREATE INDEX "idx_style_as3b_steps_style_id" ON "style_as3b_steps" ("style_id") `);
        await queryRunner.query(`CREATE INDEX "idx_draft_boms_status" ON "draft_boms" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_draft_boms_color_id" ON "draft_boms" ("color_id") `);
        await queryRunner.query(`CREATE INDEX "idx_draft_boms_style_id" ON "draft_boms" ("style_id") `);
        await queryRunner.query(`CREATE INDEX "idx_samples_status" ON "samples" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_samples_color_id" ON "samples" ("color_id") `);
        await queryRunner.query(`CREATE INDEX "idx_samples_style_id" ON "samples" ("style_id") `);
        await queryRunner.query(`CREATE INDEX "idx_colors_status" ON "colors" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_colors_style_id" ON "colors" ("style_id") `);
        await queryRunner.query(`ALTER TABLE "boms" ADD CONSTRAINT "FK_boms_style" FOREIGN KEY ("style_id") REFERENCES "styles"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "boms" ADD CONSTRAINT "FK_boms_master_po" FOREIGN KEY ("master_po_id") REFERENCES "master_pos"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "doc_files" ADD CONSTRAINT "FK_doc_files_folder" FOREIGN KEY ("folder_id") REFERENCES "doc_folders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "master_po_lines" ADD CONSTRAINT "FK_master_po_lines_master_po" FOREIGN KEY ("master_po_id") REFERENCES "master_pos"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "master_po_lines" ADD CONSTRAINT "FK_master_po_lines_po_line" FOREIGN KEY ("po_line_id") REFERENCES "po_lines"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_sizes" ADD CONSTRAINT "FK_material_sizes_material" FOREIGN KEY ("material_id") REFERENCES "materials"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_movements" ADD CONSTRAINT "FK_stock_movements_material" FOREIGN KEY ("material_id") REFERENCES "materials"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_movements" ADD CONSTRAINT "FK_stock_movements_user" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "po_lines" ADD CONSTRAINT "FK_po_lines_style" FOREIGN KEY ("style_id") REFERENCES "styles"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "line_samples" ADD CONSTRAINT "FK_line_samples_color" FOREIGN KEY ("color_id") REFERENCES "colors"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "line_color_cards" ADD CONSTRAINT "FK_line_color_cards_line_color" FOREIGN KEY ("line_color_id") REFERENCES "line_colors"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "style_version_logs" ADD CONSTRAINT "FK_style_version_logs_style" FOREIGN KEY ("style_id") REFERENCES "styles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "style_production_docs" ADD CONSTRAINT "FK_style_production_docs_style" FOREIGN KEY ("style_id") REFERENCES "styles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "style_as3b_steps" ADD CONSTRAINT "FK_style_as3b_steps_style" FOREIGN KEY ("style_id") REFERENCES "styles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "draft_boms" ADD CONSTRAINT "FK_draft_boms_style" FOREIGN KEY ("style_id") REFERENCES "styles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "draft_boms" ADD CONSTRAINT "FK_draft_boms_color" FOREIGN KEY ("color_id") REFERENCES "colors"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "draft_bom_lines" ADD CONSTRAINT "FK_draft_bom_lines_draft_bom" FOREIGN KEY ("draft_bom_id") REFERENCES "draft_boms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "draft_bom_lines" ADD CONSTRAINT "FK_draft_bom_lines_material" FOREIGN KEY ("master_material_id") REFERENCES "materials"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "materials" ADD CONSTRAINT "FK_materials_material_group" FOREIGN KEY ("material_group_id") REFERENCES "material_groups"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "samples" ADD CONSTRAINT "FK_samples_style" FOREIGN KEY ("style_id") REFERENCES "styles"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "samples" ADD CONSTRAINT "FK_samples_color" FOREIGN KEY ("color_id") REFERENCES "colors"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "colors" ADD CONSTRAINT "FK_colors_style" FOREIGN KEY ("style_id") REFERENCES "styles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
